apiVersion: v1 
kind: Pod
metdata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx-latest
    ports:
    - name: nginxport
      ContainerPort: 80